# 使用 Fedora 作为基础镜像
FROM arm64/fedora

# 设置维护者信息（可选）
LABEL maintainer="JackyAnn <JackyAnn@foxmail.com>"
LABEL description "pulsar"

# 更新系统并安装 OpenJDK
RUN dnf -y update && dnf -y install java-latest-openjdk-jmods && dnf clean all

# 创建目录并下载并解压 Apache Pulsar
RUN mkdir -p /opt/pulsar && \
    wget https://archive.apache.org/dist/pulsar/pulsar-3.1.0/apache-pulsar-3.1.0-bin.tar.gz -O /opt/pulsar/pulsar.tar.gz && \
    tar -xzf /opt/pulsar/pulsar.tar.gz --strip-components=1 -C /opt/pulsar && \
    rm /opt/pulsar/pulsar.tar.gz

# 使用 EXPOSE 指令指定容器内 PostgreSQL 服务监听的端口
EXPOSE 6650 8080

# 设置工作目录
WORKDIR /opt/pulsar

# 使用 CMD 指令指定容器启动时要运行的命令
CMD ["/opt/pulsar/bin", "standalone"]
