name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        for dir in jdk redis postgresql pulsar; do
          cd $dir
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$dir:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/$dir:latest
          cd ..
        done
